ignored = ["github.com/codelingo/codelingo/tenets*"]

[[constraint]]
  name = "github.com/codelingo/lingo"
  branch = "master"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  branch = "master"
  name = "github.com/marcinwyszynski/directory_tree"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "^1.5.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[prune]
  go-tests = true
  unused-packages = true
