funcs:
  - name: beginsWith
    type: asserter
    body: |
      function (start, str) {
        return str.indexOf(start) == 0
      }
specs:
  - name: well-named-interface
    actions:
      codelingo/docs:
        title: Well Named Interface
        body: |
          Please consider the package name when selecting an interface name, and avoid redundancy. e.g. `storage.Interface` is better than `storage.StorageInterface`.
      codelingo/review:
        comment: Interface name {{interfaceName}} has name of package {{packageName} redundantly prefixed.
    query: |
      import codelingo/ast/go
            
      go.file(depth = any):
        go.ident:
          name as packageName
        go.gen_decl(depth = 1):
          go.type_spec:
            @review comment
            go.ident:
              name as interfaceName
              beginsWith(packageName, interfaceName)
            go.interface_type
