version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:2.0
    working_directory: /go/src/github.com/codelingo/codelingo
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -v
      - run: go test $(go list ./... 2>/dev/null  | grep -v /tenets/ | grep -v /vendor)
