funcs:
  - name: missingListSuffix
    type: asserter
    body: |
      function (str) {
        return !str.match(/.*List$/);
      }
tenets:
  - name: well-named-lists
    actions:
      codelingo/docs:
        title: Well Named Lists
        body: |
          The name of a list kind must end with List.
      codelingo/review:
        comment: The kind `{{listName}}` is a collection of resources and its name must end in `List`.
    query: |
      import codelingo/ast/go
      
      go.gen_decl:
        go.type_spec:
          @review comment
          go.ident:
            name as listName
            missingListSuffix(listName)
          go.struct_type:
            go.field_list:
              go.field:
                go.selector_expr:
                  go.ident:
                    name == "metav1"
                  go.ident:
                    name == "TypeMeta"
              go.field:
                go.selector_expr:
                  go.ident:
                    name == "metav1"
                  go.ident:
                    name == "ListMeta"
